apiVersion: apps/v1
kind: Deployment
metadata:
  name: amiq-mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amiq-mssql
  template:
    metadata:
      labels:
        app: amiq-mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: 'Express'
            - name: ACCEPT_EULA
              value: 'Y'
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: amiqmssqldb
      volumes:
        - name: amiqmssqldb
          persistentVolumeClaim:
            claimName: mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: amiq-mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: amiq-mssql
  ports:
    - name: amiq-mssql
      protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: amiq-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: amiq-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
