export const GET_CHAT_PREVIEWS = 'GET_CHAT_PREVIEWS'
export const SET_CHAT_PREVIEWS = 'SET_CHAT_PREVIEWS'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const MESSAGE_CREATED = 'MESSAGE_CREATED'