export const GET_GROUP_POST_COMMENTS = "GET_GROUP_POST_COMMENTS";
export const SET_GROUP_POST_COMMENTS = "SET_GROUP_POST_COMMENTS";
export const CREATE_GROUP_POST_COMMENT = "CREATE_GROUP_POST_COMMENT";
export const SET_CREATED_GROUP_POST_COMMENT = "SET_CREATED_GROUP_POST_COMMENT";