export const GET_PARTICIPANTS = "GET_PARTICIPANTS";
export const SET_PARTICIPANTS = "SET_PARTICIPANTS";
export const CLEAR_GROUP_PARTICIPANTS = "CLEAR_GROUP_PARTICIPANTS";
export const REMOVE_GROUP_PARTICIPANT = "REMOVE_GROUP_PARTICIPANT";
export const BLOCK_USER_IN_GROUP= "BLOCK_USER_IN_GROUP";