export const GET_GROUP_EVENTS = "GET_GROUP_EVENTS";
export const SET_GROUP_EVENTS = "SET_GROUP_EVENTS";
export const CANCEL_EVENT = "CANCEL_EVENT";
export const SET_CANCELLED_EVENT = "SET_CANCELLED_EVENT";
export const REOPEN_EVENT = "REOPEN_EVENT";
export const SET_REOPEN_EVENT = "SET_REOPEN_EVENT";
export const SET_EVENT_VISIBILITY = "SET_EVENT_VISIBILITY";
