apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: groupservice
  template:
    metadata:
      labels:
        app: groupservice
    spec:
      containers:
        - name: groupservice
          image: amiqservicesgroup
          imagePullPolicy: Never
          env:
            - name: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
              value: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: group-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: groupservice
  ports:
    - name: groupservice-1
      protocol: TCP
      port: 81
      targetPort: 80
    - name: groupservice-2
      protocol: TCP
      port: 82
      targetPort: 80
    - name: groupservice-3
      protocol: TCP
      port: 83
      targetPort: 80
