apiVersion: v1
kind: Service
metadata:
  name: ocelotnpservice-srv
spec:
  type: NodePort
  selector:
    app: ocelotservice
  ports:
    - name: ocelotservice
      protocol: TCP
      port: 80
      targetPort: 80
